# Generated by Django 4.2.10 on 2024-03-13 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("date_of_establishement", models.DateField(verbose_name="Date")),
                ("vendor_id", models.CharField(max_length=6)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "last_updated",
                    models.DateField(auto_now_add=True, verbose_name="Date"),
                ),
                ("company_url", models.URLField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("software_type", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=200)),
                ("clients", models.CharField()),
                ("cloud_based", models.BooleanField(default=False)),
                ("cloud_native", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search_page.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=30)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "company",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search_page.company",
                    ),
                ),
            ],
        ),
    ]
